site_name: CM Blocks
theme:
  name: material
  palette:
    primary: custom
extra_css:
  - css/extra.css
nav:
  - Introduction: index.md
  - Installation: installation.md
  - Blocks Template: template.md