site_name: CM Blocks
theme:
  name: material
  palette:
    primary: custom
    accent: custom
  font:
    text: Sofia Pro
extra_css:
  - css/extra.css
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search:
        lang: en
        separator: '[\s\-]+'
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
nav:
  - Introduction: index.md
  - Installation: installation.md
  - Blocks Template: template.md
  - Blocks:
    - Slider: slider.md
    - Accordion: accordion.md
    - Counter: counter.md
    - Progress Bar: progress-bar.md
    - Masonry Gallery: masonry-gallery.md
    - Countdown: countdown.md
    - Icon : icon.md
    - Icon List : icon-list.md
    - Icon Box : icon-box.md
    - Social Share : social-share.md
    - Time to Read : time-to-read.md
    - Star Rating : star-rating.md
    - Timeline : timeline.md
  - Features:
      - Block Visibility: features/block-visibility.md
      - Site: features/site.md
      - Scroll to Top: features/scroll-to-top.md
  - Design Library:
      - Introduction: design-library/index.md
      - Features: design-library/features.md
      - Choose a Pattern: design-library/choose-pattern.md
  - Kits:
      - Introduction: kits/index.md
      - Features: kits/features.md
      - Choose a Kit: kits/choose-kits.md
  - Favorites:
      - Introduction: favorites/index.md
      - Features: favorites/features.md
      - Add, Remove or Display Favorites: favorites/add-remove-favorites.md
  - Simple Popup Block Plugin:
      - Introduction: simple-popup-block/index.md
      - Installation: simple-popup-block/installation.md
      - Choose a Template: simple-popup-block/template.md
      - Popup Trigger: simple-popup-block/popup-trigger.md
      - Popup Behavior: simple-popup-block/popup-behavior.md
      - Popup Condition: simple-popup-block/popup-condition.md
      - Dimension: simple-popup-block/dimension.md
      - Close Button: simple-popup-block/close-button.md
      - Tutorial:
          - 'Display On Whole Site': 'simple-popup-block/display-on-whole-site.md'
          - 'Show popup on click': 'simple-popup-block/trigger-on-click.md'
          - 'Show Video in popup': 'simple-popup-block/embed-video-in-popup.md'
  - Sticky Header: sticky-header/index.md
  - General Theme: general-theme/index.md
  -  Theme:
      - CM News: cm-news/index.md
      - CM Blog: cm-blog/index.md
      - CM News Pro: cm-news-pro/index.md



        
        